// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/dexidp/dex" | string
		tag:        *"v2.46.0" | string
		digest:     *"sha256:933fcd3f523338c847b88ef84a7145fb2fcb7b9917f08418612afeaaa2001777" | string
	}
}
