// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/dexidp/dex" | string
		tag:        *"v2.45.1" | string
		digest:     *"sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462" | string
	}
}
