// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/fluent/fluent-operator/fluent-operator" | string
		tag:        *"v3.10.1" | string
		digest:     *"sha256:be978534f9fc1b998dc822c5eaa95b4e88e6a853a9739fd84fe10b44fcb9a97b" | string
	}
}
