// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/fluent/fluent-operator/fluent-operator" | string
		tag:        *"v3.10.0" | string
		digest:     *"sha256:3108194a4ecc063f55371476775ddb8a36a1c7613fd03cfd13d05141e1b0bd0e" | string
	}
}
