// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/fluent/fluent-operator/fluent-operator" | string
		tag:        *"v3.9.0" | string
		digest:     *"sha256:705375468232d8d39d47c60d55296b1587501fc1cb4f2f313e7e7b4ad82cc3ed" | string
	}
}
