// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/external-secrets/external-secrets" | string
		tag:        *"v2.9.0" | string
		digest:     *"sha256:44eb290f1c7f5d8f4eec2168cea4a6cfbc72a955c6781eb835e1c40700475dbd" | string
	}
}
