// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/external-secrets/external-secrets" | string
		tag:        *"v2.11.0" | string
		digest:     *"sha256:66fb710878cbf3eba4a927e35c5d75e29a202c9bab238aad64bfb23b786b962b" | string
	}
}
