// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/external-secrets/external-secrets" | string
		tag:        *"v2.10.0" | string
		digest:     *"sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1" | string
	}
}
