// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"external-dns": {
		repository: "registry.k8s.io/external-dns/external-dns"
		tag:        "v0.21.0"
		digest:     ""
	}
}
