// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"docker.io/envoyproxy/gateway" | string
		tag:        *"v1.9.2" | string
		digest:     *"sha256:9d67017c442a70e6ae9f1a358e6c80eb653c67c2e40823d9a991e0daf37ba926" | string
	}
	proxy: image: {
		repository: *"docker.io/envoyproxy/envoy" | string
		tag:        *"distroless-v1.39.1" | string
		digest:     *"sha256:eb2c01c13125d1629637cb4e4cce7207009fb7cc2c8027f9742758549d15b6f4" | string
	}
	rateLimit: image: {
		repository: *"docker.io/envoyproxy/ratelimit" | string
		tag:        *"0482748e" | string
		digest:     *"sha256:5fdd8e3ae335ab6d64316f8d2fd9a886830075cbbb40a1d8065c869275909162" | string
	}
}
