// Code generated by upengine. DO NOT EDIT.

package config

// The container images tracked from the upstream releases.
#defaultImages: {
	"controller": {
		repository: "quay.io/jetstack/cert-manager-controller"
		tag:        "v1.21.1"
		digest:     "sha256:416a2d76870d996460e62bd7f521bf14fa017be9e3e904aab92163a331fcb61a"
	}
	"webhook": {
		repository: "quay.io/jetstack/cert-manager-webhook"
		tag:        "v1.21.1"
		digest:     "sha256:d8b3961b51c8c7320633f8208dc46bf88aa13804d0f7cbe48a096b2c523cee42"
	}
	"cainjector": {
		repository: "quay.io/jetstack/cert-manager-cainjector"
		tag:        "v1.21.1"
		digest:     "sha256:ccf6b919ec0500745a47a910118f834f9636d0aac1ff221245cd2557ed8c7c98"
	}
	"acmesolver": {
		repository: "quay.io/jetstack/cert-manager-acmesolver"
		tag:        "v1.21.1"
		digest:     "sha256:dbc7cc1354f603918e7c5af7f55a0a620537394452c93a565bde75c6f48e8837"
	}
}
