// Code generated by upengine. DO NOT EDIT.

package config

// The container images tracked from the upstream releases.
#defaultImages: {
	"controller": {
		repository: "quay.io/jetstack/cert-manager-controller"
		tag:        "v1.21.1"
		digest:     ""
	}
	"webhook": {
		repository: "quay.io/jetstack/cert-manager-webhook"
		tag:        "v1.21.1"
		digest:     ""
	}
	"cainjector": {
		repository: "quay.io/jetstack/cert-manager-cainjector"
		tag:        "v1.21.1"
		digest:     ""
	}
	"acmesolver": {
		repository: "quay.io/jetstack/cert-manager-acmesolver"
		tag:        "v1.21.1"
		digest:     ""
	}
}
