// Copyright 2026 Stefan Prodan.
// SPDX-License-Identifier: Apache-2.0

import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { MODULES_DIR } from "./paths.ts";
import { mustRun, run } from "./proc.ts";
import type { ImageRef } from "./types.ts";

/**
 * Characters allowed in the upstream-controlled strings rendered into CUE
 * quoted literals (image keys, repositories, tags, digests). Quotes,
 * backslashes and control characters are rejected so hostile manifest data
 * cannot inject CUE syntax.
 */
const CUE_SAFE_RE = /^[A-Za-z0-9][A-Za-z0-9._/:@+-]*$/;

function cueSafe(value: string, label: string): string {
  if (value !== "" && !CUE_SAFE_RE.test(value)) {
    throw new Error(`${label} '${value}' contains characters not allowed in generated CUE`);
  }
  return value;
}

/**
 * Renders a module's generated templates/versions.cue holding the image
 * defaults tracked from the upstream releases. Key order follows the
 * sources.ts declaration; the output is in canonical timoni fmt form.
 */
export function renderVersionsCue(images: Record<string, ImageRef>): string {
  const lines = [
    "// Code generated by upengine. DO NOT EDIT.",
    "",
    "package templates",
    "",
    "// The container images tracked from the upstream releases.",
    "#defaultImages: {",
  ];
  for (const [key, ref] of Object.entries(images)) {
    lines.push(`\t"${cueSafe(key, "image key")}": {`);
    lines.push(`\t\trepository: "${cueSafe(ref.repository, "image repository")}"`);
    lines.push(`\t\ttag:        "${cueSafe(ref.tag, "image tag")}"`);
    lines.push(`\t\tdigest:     "${cueSafe(ref.digest, "image digest")}"`);
    lines.push("\t}");
  }
  lines.push("}", "");
  return lines.join("\n");
}

/** Writes the generated files of a module bump: versions.cue, VERSION and,
 * for modules that track upstream CRDs, templates/crds.cue. */
export async function writeModuleFiles(
  name: string,
  images: Record<string, ImageRef>,
  moduleVersion: string,
  crdManifest: string | null = null,
): Promise<void> {
  const moduleDir = join(MODULES_DIR, name);
  const versionsCue = join(moduleDir, "templates/versions.cue");
  await Bun.write(versionsCue, renderVersionsCue(images));
  await Bun.write(join(moduleDir, "VERSION"), `${moduleVersion}\n`);
  // Only the generated files are formatted — the engine never rewrites
  // curated templates.
  await mustRun(["timoni", "fmt", versionsCue]);
  if (crdManifest !== null) {
    await writeCrdsCue(name, crdManifest);
  }
}

/** Renders the upstream CRD manifest into the generated templates/crds.cue,
 * keyed by lowercased kind and metadata.name (the flux-aio convention). */
async function writeCrdsCue(name: string, crdManifest: string): Promise<void> {
  const crdsCue = join(MODULES_DIR, name, "templates/crds.cue");
  const tmp = join(tmpdir(), `upengine-${name}-crds.yaml`);
  await Bun.write(tmp, crdManifest);
  try {
    await mustRun([
      "cue", "import", "-f", "-o", crdsCue,
      "-l", "strings.ToLower(kind)", "-l", "metadata.name",
      "-p", "templates", tmp,
    ]);
  } finally {
    await rm(tmp, { force: true });
  }
  const imported = await Bun.file(crdsCue).text();
  await Bun.write(crdsCue, `// Code generated by upengine. DO NOT EDIT.\n\n${imported}`);
  await mustRun(["timoni", "fmt", crdsCue]);
}

/** Restores a module's generated files from git after a failed bump, so a
 * later run never skips on an unverified VERSION. */
export async function restoreModuleFiles(name: string, hasCrds: boolean): Promise<void> {
  const moduleDir = join(MODULES_DIR, name);
  await mustRun([
    "git",
    "checkout",
    "--",
    join(moduleDir, "templates/versions.cue"),
    join(moduleDir, "VERSION"),
  ]);
  if (hasCrds) {
    // During a module's first sync the file is not in git yet: deleting
    // the freshly generated one restores the pre-sync state.
    const crdsCue = join(moduleDir, "templates/crds.cue");
    const restored = await run(["git", "checkout", "--", crdsCue]);
    if (restored.exitCode !== 0) {
      await rm(crdsCue, { force: true });
    }
  }
}

/** The digest of a module's generated files, recorded in the history
 * manifest so a hand-edited or corrupted state re-syncs instead of being
 * skipped forever. */
export async function generatedFilesDigest(name: string): Promise<string> {
  const moduleDir = join(MODULES_DIR, name);
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(await Bun.file(join(moduleDir, "templates/versions.cue")).text());
  hasher.update(await Bun.file(join(moduleDir, "VERSION")).text());
  const crdsCue = Bun.file(join(moduleDir, "templates/crds.cue"));
  if (await crdsCue.exists()) {
    hasher.update(await crdsCue.text());
  }
  return `sha256:${hasher.digest("hex")}`;
}

/**
 * Post-bump guards: the module must vet clean with the debug values (which
 * enable every optional object) and render at least one Kubernetes resource
 * with the defaults. Failures surface the tool output.
 */
export async function verifyModule(name: string): Promise<void> {
  const moduleDir = join(MODULES_DIR, name);
  await mustRun(["timoni", "mod", "vet", moduleDir, "--debug"]);
  const build = await mustRun(["timoni", "-n", name, "build", name, moduleDir]);
  if (!/^kind: /m.test(build)) {
    throw new Error(`timoni build of ${name} produced no resources`);
  }
}
