// Copyright 2026 Stefan Prodan.
// SPDX-License-Identifier: Apache-2.0

import { readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { crdChannels } from "./config.ts";
import { MODULES_DIR } from "./paths.ts";
import { mustRun, run } from "./proc.ts";
import type { ImageRef, ModuleSource } from "./types.ts";

/**
 * Characters allowed in the upstream-controlled strings rendered into CUE
 * quoted literals (image keys, repositories, tags, digests). Quotes,
 * backslashes and control characters are rejected so hostile manifest data
 * cannot inject CUE syntax.
 */
const CUE_SAFE_RE = /^[A-Za-z0-9][A-Za-z0-9._/:@+-]*$/;

function cueSafe(value: string, label: string): string {
  if (value !== "" && !CUE_SAFE_RE.test(value)) {
    throw new Error(`${label} '${value}' contains characters not allowed in generated CUE`);
  }
  return value;
}

/** The generated images.cue location: the module root, where the image
 * defaults unify into the values. */
export function imagesCuePath(name: string): string {
  return join(MODULES_DIR, name, "images.cue");
}

// A single camelCase CUE label of an image's values path, rendered
// unquoted into the generated images.cue.
const PATH_LABEL_RE = /^[a-zA-Z][A-Za-z0-9]*$/;

function pathLabels(path: string): string[] {
  const labels = path.split(".");
  for (const label of labels) {
    if (!PATH_LABEL_RE.test(label)) {
      throw new Error(`values path '${path}' is not a dotted list of CUE labels`);
    }
  }
  return labels;
}

/** The generated crds file of one channel; the "" channel of a single-input
 * module renders to the channel-less templates/crds.cue. */
function crdsCuePath(name: string, channel: string): string {
  const file = channel === "" ? "templates/crds.cue" : `templates/crds_${channel}.cue`;
  return join(MODULES_DIR, name, file);
}

/** Every generated crds file of a module, in channel declaration order. */
export function crdsCuePaths(name: string, crds: ModuleSource["crds"]): string[] {
  return Object.keys(crdChannels(crds)).map((channel) => crdsCuePath(name, channel));
}

/** Matches every engine-generated file path inside a module directory. */
export const GENERATED_FILE_RE = /modules\/[^/]+\/images\.cue$|templates\/crds(_[a-z0-9-]+)?\.cue$/;

/** Whether every generated file the current source declaration expects
 * exists on disk. A missing file (e.g. crds or images freshly added to
 * sources.ts) must trigger a re-sync instead of being skipped. */
export async function generatedFilesPresent(source: ModuleSource): Promise<boolean> {
  if (
    Object.keys(source.images ?? {}).length > 0 &&
    !(await Bun.file(imagesCuePath(source.name)).exists())
  ) {
    return false;
  }
  for (const path of crdsCuePaths(source.name, source.crds)) {
    if (!(await Bun.file(path).exists())) {
      return false;
    }
  }
  return true;
}

/**
 * Renders a module's generated images.cue holding the image defaults
 * tracked from the upstream releases, written into the values at each
 * image's declared path as overridable defaults. Key order follows the
 * sources.ts declaration; the output is in canonical timoni fmt form.
 */
export function renderImagesCue(
  images: Record<string, ImageRef>,
  paths: Record<string, string>,
): string {
  const lines = [
    "// Code generated by upengine. DO NOT EDIT.",
    "",
    "package main",
    "",
    "// The container images tracked from the upstream releases.",
    "values: {",
  ];
  for (const [key, ref] of Object.entries(images)) {
    const labels = pathLabels(paths[key] ?? "image");
    lines.push(`\t${labels.join(": ")}: {`);
    lines.push(`\t\trepository: *"${cueSafe(ref.repository, "image repository")}" | string`);
    lines.push(`\t\ttag:        *"${cueSafe(ref.tag, "image tag")}" | string`);
    lines.push(`\t\tdigest:     *"${cueSafe(ref.digest, "image digest")}" | string`);
    lines.push("\t}");
  }
  lines.push("}", "");
  return lines.join("\n");
}

/** Writes the generated files of a module bump: images.cue (skipped for
 * image-less modules), VERSION and, for modules that track upstream CRDs,
 * one generated crds file per channel. */
export async function writeModuleFiles(
  name: string,
  images: Record<string, ImageRef>,
  moduleVersion: string,
  crdManifests: Record<string, string> = {},
  paths: Record<string, string> = {},
): Promise<void> {
  const moduleDir = join(MODULES_DIR, name);
  if (Object.keys(images).length > 0) {
    const imagesCue = imagesCuePath(name);
    await Bun.write(imagesCue, renderImagesCue(images, paths));
    // Only the generated files are formatted — the engine never rewrites
    // curated templates.
    await mustRun(["timoni", "fmt", imagesCue]);
  } else {
    // A module that dropped its images must not keep stale defaults.
    await rm(imagesCuePath(name), { force: true });
  }
  await Bun.write(join(moduleDir, "VERSION"), `${moduleVersion}\n`);
  // Generated crds files of channels no longer declared (or the flat
  // crds.cue of a module migrated to channels, and vice versa) are
  // removed so the worktree only carries what the declaration produces.
  const templatesDir = join(moduleDir, "templates");
  const expected = new Set(Object.keys(crdManifests).map((channel) => crdsCuePath(name, channel)));
  for (const entry of await readdir(templatesDir)) {
    const path = join(templatesDir, entry);
    if (/^crds(_[a-z0-9-]+)?\.cue$/.test(entry) && !expected.has(path)) {
      await rm(path, { force: true });
    }
  }
  for (const [channel, manifest] of Object.entries(crdManifests)) {
    await writeCrdsCue(name, channel, manifest);
  }
}

/** Renders an upstream CRD manifest into the generated crds file of one
 * channel, keyed by lowercased kind and metadata.name (the flux-aio
 * convention). Channel imports are nested under `crds: <channel>:` so the
 * same-named CRDs of two channels never unify. */
async function writeCrdsCue(name: string, channel: string, crdManifest: string): Promise<void> {
  const crdsCue = crdsCuePath(name, channel);
  const tmp = join(tmpdir(), `upengine-${name}-crds.yaml`);
  await Bun.write(tmp, crdManifest);
  // A quoted -l expression is a literal CUE label, prepended to the path
  // of every imported document.
  const labels =
    channel === "" ? [] : ["-l", `"crds"`, "-l", `"${channel}"`];
  try {
    await mustRun([
      "cue", "import", "-f", "-o", crdsCue,
      ...labels,
      "-l", "strings.ToLower(kind)", "-l", "metadata.name",
      "-p", "templates", tmp,
    ]);
  } finally {
    await rm(tmp, { force: true });
  }
  const imported = await Bun.file(crdsCue).text();
  await Bun.write(crdsCue, `// Code generated by upengine. DO NOT EDIT.\n\n${imported}`);
  await mustRun(["timoni", "fmt", crdsCue]);
}

/** Restores a module's generated files from git after a failed bump, so a
 * later run never skips on an unverified VERSION. */
export async function restoreModuleFiles(
  name: string,
  crds: ModuleSource["crds"],
): Promise<void> {
  const moduleDir = join(MODULES_DIR, name);
  await restoreOrRemove(imagesCuePath(name));
  await restoreOrRemove(join(moduleDir, "VERSION"));
  for (const path of crdsCuePaths(name, crds)) {
    await restoreOrRemove(path);
  }
}

/** Restores one generated file from git; during a module's first sync
 * the file is not in git yet, so deleting the freshly generated one
 * restores the pre-sync state. Each file is restored independently — a
 * single untracked path must not abort the rollback of the others. */
async function restoreOrRemove(path: string): Promise<void> {
  const restored = await run(["git", "checkout", "--", path]);
  if (restored.exitCode !== 0) {
    await rm(path, { force: true });
  }
}

/** The digest of a module's generated files, recorded in the history
 * manifest so a hand-edited or corrupted state re-syncs instead of being
 * skipped forever. */
export async function generatedFilesDigest(
  name: string,
  crds?: ModuleSource["crds"],
): Promise<string> {
  const moduleDir = join(MODULES_DIR, name);
  const hasher = new Bun.CryptoHasher("sha256");
  const imagesCue = Bun.file(imagesCuePath(name));
  if (await imagesCue.exists()) {
    hasher.update(await imagesCue.text());
  }
  hasher.update(await Bun.file(join(moduleDir, "VERSION")).text());
  for (const path of crdsCuePaths(name, crds)) {
    const crdsCue = Bun.file(path);
    if (await crdsCue.exists()) {
      hasher.update(await crdsCue.text());
    }
  }
  return `sha256:${hasher.digest("hex")}`;
}

/**
 * Post-bump guards: the module must vet clean with the debug values (which
 * enable every optional object) and render at least one Kubernetes resource
 * with the defaults. Failures surface the tool output.
 */
export async function verifyModule(name: string): Promise<void> {
  const moduleDir = join(MODULES_DIR, name);
  await mustRun(["timoni", "mod", "vet", moduleDir, "--debug"]);
  const build = await mustRun(["timoni", "-n", name, "build", name, moduleDir]);
  if (!/^kind: /m.test(build)) {
    throw new Error(`timoni build of ${name} produced no resources`);
  }
}
