// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"quay.io/prometheus-operator/prometheus-operator" | string
		tag:        *"v0.94.1" | string
		digest:     *"sha256:7c88d4e7bae63bd8d0f8da986054337c23b4472fa8d3c6817f5bc4b8407a2d6a" | string
	}
	configReloader: image: {
		repository: *"quay.io/prometheus-operator/prometheus-config-reloader" | string
		tag:        *"v0.94.1" | string
		digest:     *"sha256:06b52bd4dbe3ed6dd5905aadaf8b9987d9da4c31d37bb86deaadae68cee2d26b" | string
	}
}
