// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"quay.io/prometheus-operator/prometheus-operator" | string
		tag:        *"v0.94.0" | string
		digest:     *"sha256:cf153f64d6c38113fceb2cda7642365ea887f71edd7888f054e43e54cf177e55" | string
	}
	configReloader: image: {
		repository: *"quay.io/prometheus-operator/prometheus-config-reloader" | string
		tag:        *"v0.94.0" | string
		digest:     *"sha256:142a1f11df8dd165f00375b0b1826aecb9c9adeb05c39855893138d7c7575ff7" | string
	}
}
