// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"quay.io/prometheus-operator/prometheus-operator" | string
		tag:        *"v0.93.1" | string
		digest:     *"sha256:e52bb28fd41c98dd407c7a8cba8bdcfe7eabd7447e250afaf1fe7bb816dedbff" | string
	}
	configReloader: image: {
		repository: *"quay.io/prometheus-operator/prometheus-config-reloader" | string
		tag:        *"v0.93.1" | string
		digest:     *"sha256:428f088fe6fe07ab138bda92113664b04848a1dc408e4d3680a60ecdb55d1a65" | string
	}
}
