// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"registry.k8s.io/external-dns/external-dns" | string
		tag:        *"v0.22.0" | string
		digest:     *"sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf" | string
	}
}
