// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"registry.k8s.io/external-dns/external-dns" | string
		tag:        *"v0.23.0" | string
		digest:     *"sha256:1854499e2b08cee47c40a08e356bff20dcb192dbcfde8378fc3f900f12cad5a3" | string
	}
}
