// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"registry.k8s.io/external-dns/external-dns" | string
		tag:        *"v0.21.0" | string
		digest:     *"sha256:f53faaf71cb270d1ca9dce6ea0c94bfebf1a18696263487f0fbc74b9bf2bd7ff" | string
	}
}
