// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"quay.io/prometheus/node-exporter" | string
		tag:        *"v1.12.1" | string
		digest:     *"sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0" | string
	}
}
