// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/controlplaneio-fluxcd/flux-operator" | string
		tag:        *"v0.61.0" | string
		digest:     *"sha256:71041d9fff7f7b05f1a8123ebe73c73b7b156f4aacfe1e8e19b5aa953a98892c" | string
	}
}
