// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/controlplaneio-fluxcd/flux-operator" | string
		tag:        *"v0.58.0" | string
		digest:     *"sha256:1c919ce1e28716f817ded65c06df0b7a8269542387d5a2ce50212450473c6209" | string
	}
}
