// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"ghcr.io/controlplaneio-fluxcd/flux-operator" | string
		tag:        *"v0.59.0" | string
		digest:     *"sha256:29421fe9a49a533ac99a5b7779e1a5fffa3227b16ddfcefe1e3b14e5c20a1767" | string
	}
}
