// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"prometheus-operator": {
		repository: "quay.io/prometheus-operator/prometheus-operator"
		tag:        "v0.93.0"
		digest:     ""
	}
	"prometheus-config-reloader": {
		repository: "quay.io/prometheus-operator/prometheus-config-reloader"
		tag:        "v0.93.0"
		digest:     ""
	}
}
