// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"kube-state-metrics": {
		repository: "registry.k8s.io/kube-state-metrics/kube-state-metrics"
		tag:        "v2.19.1"
		digest:     ""
	}
}
