// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"kube-state-metrics": {
		repository: "registry.k8s.io/kube-state-metrics/kube-state-metrics"
		tag:        "v2.19.1"
		digest:     "sha256:85108987d044b18a098126732f98602df408888c0f7d456241f5abefb9744bc1"
	}
}
