// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	recommender: image: {
		repository: *"registry.k8s.io/autoscaling/vpa-recommender" | string
		tag:        *"1.7.1" | string
		digest:     *"sha256:89cea705535f9d8df6e62d5084916ec447e85d64369cfff2f7c6ac9d1cc5cd1e" | string
	}
	updater: image: {
		repository: *"registry.k8s.io/autoscaling/vpa-updater" | string
		tag:        *"1.7.1" | string
		digest:     *"sha256:feb42a5269708d065d5a43c5379d0e4700c3eca333231723d6a7c24f222ab446" | string
	}
	admissionController: image: {
		repository: *"registry.k8s.io/autoscaling/vpa-admission-controller" | string
		tag:        *"1.7.1" | string
		digest:     *"sha256:be29624f7f12a0b6f7fe18e2e042195eb6e39ae37d4490000f2643a480873572" | string
	}
}
