// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	controller: image: {
		repository: *"quay.io/jetstack/cert-manager-controller" | string
		tag:        *"v1.21.2" | string
		digest:     *"sha256:70f532fd9cfde0b09d55687200942399d89838bc2d5d5b45152eb799a15912b8" | string
	}
	webhook: image: {
		repository: *"quay.io/jetstack/cert-manager-webhook" | string
		tag:        *"v1.21.2" | string
		digest:     *"sha256:a60e2dac46dbb8a7f3df95c54ce941012f54c2fe022f0ee55aaa1ab40ed957ae" | string
	}
	cainjector: image: {
		repository: *"quay.io/jetstack/cert-manager-cainjector" | string
		tag:        *"v1.21.2" | string
		digest:     *"sha256:c85268c64f2e0e76684bf5fe8906caff34b82523561c6affe0fae3546bd87562" | string
	}
	acmesolver: image: {
		repository: *"quay.io/jetstack/cert-manager-acmesolver" | string
		tag:        *"v1.21.2" | string
		digest:     *"sha256:699b40d622211ab7accad8a21b04c5fbaa1841ef7a12621e8de492dbe27b2503" | string
	}
}
