// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"registry.k8s.io/kube-state-metrics/kube-state-metrics" | string
		tag:        *"v2.19.1" | string
		digest:     *"sha256:85108987d044b18a098126732f98602df408888c0f7d456241f5abefb9744bc1" | string
	}
}
