// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"registry.k8s.io/kube-state-metrics/kube-state-metrics" | string
		tag:        *"v2.20.0" | string
		digest:     *"sha256:42cfe3723a5f058171c627537fb57a3ea0f26e4380fa18555a95cb1a1b4cfc5b" | string
	}
}
