// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"quay.io/jetstack/trust-manager" | string
		tag:        *"v0.24.0" | string
		digest:     *"sha256:a7c1d71cad37b404738192213e3801dbf89fe797e72664b0ff0d498db35cea74" | string
	}
	defaultPackage: image: {
		repository: *"quay.io/jetstack/trust-pkg-debian-trixie" | string
		tag:        *"20250419.1" | string
		digest:     *"sha256:17084a794d1e75065c9047438e2a6167907771fe78d7e4b5d4373a4b1d4e0494" | string
	}
}
