// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"quay.io/jetstack/trust-manager" | string
		tag:        *"v0.25.0" | string
		digest:     *"sha256:0521921c2a46d14d0417336b20bcde69215ef3164f2977cc939d53c6e5224a17" | string
	}
	defaultPackage: image: {
		repository: *"quay.io/jetstack/trust-pkg-debian-trixie" | string
		tag:        *"20250419.2" | string
		digest:     *"sha256:3093d4f6634fbd9eaf6a70a06d809132850d7cae30da82396d3b1f884c1135e7" | string
	}
}
