// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"envoy-gateway": {
		repository: "docker.io/envoyproxy/gateway"
		tag:        "v1.8.3"
		digest:     ""
	}
}
