// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"envoy-gateway": {
		repository: "docker.io/envoyproxy/gateway"
		tag:        "v1.8.3"
		digest:     "sha256:e7a8c70537628bf996e5dec5c4c835704b4b9f4f715a74cf361bea30608c49ac"
	}
}
