package templates

import (
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	timoniv1 "timoni.sh/core/v1alpha1"
)

#Deployment: appsv1.#Deployment & {
	_config: #Config

	// The affinity rules generated from the affinity values;
	// the anti-affinity presets match the instance selector labels.
	_affinity: timoniv1.#Affinity & {
		#Values:      _config.affinity
		#MatchLabels: _config.selector.labels
	}

	apiVersion: "apps/v1"
	kind:       "Deployment"
	metadata:   _config.metadata
	if _config.deploymentAnnotations != _|_ {
		metadata: annotations: _config.deploymentAnnotations
	}

	// The TLS certificates secret mounted when the certificate
	// is not generated by metrics-server itself.
	_certsSecretName: [
		if _config.tls.type == "existingSecret" && _config.tls.existingSecret.name != "" {
			_config.tls.existingSecret.name
		},
		_config.metadata.name,
	][0]

	spec: appsv1.#DeploymentSpec & {
		replicas: _config.replicas
		if _config.revisionHistoryLimit != _|_ {
			revisionHistoryLimit: _config.revisionHistoryLimit
		}
		if _config.strategy != _|_ {
			strategy: _config.strategy
		}

		// With hostNetwork, the default RollingUpdate strategy deadlocks:
		// the new pod cannot bind the host port while the old one holds it.
		if _config.strategy == _|_ && _config.hostNetwork {
			strategy: {
				type: "RollingUpdate"
				rollingUpdate: maxUnavailable: 1
			}
		}
		selector: matchLabels: _config.selector.labels
		template: {
			metadata: {
				labels: _config.selector.labels
				if _config.podLabels != _|_ {
					labels: _config.podLabels
				}
				if _config.podAnnotations != _|_ {
					annotations: _config.podAnnotations
				}
			}
			spec: corev1.#PodSpec & {
				serviceAccountName:           _config.serviceAccount.name
				automountServiceAccountToken: _config.automountServiceAccountToken
				priorityClassName:            _config.priorityClassName
				if _config.hostNetwork {
					hostNetwork: true
				}
				if _config.schedulerName != _|_ {
					schedulerName: _config.schedulerName
				}
				if _config.terminationGracePeriodSeconds != _|_ {
					terminationGracePeriodSeconds: _config.terminationGracePeriodSeconds
				}
				if _config.dnsConfig != _|_ {
					dnsConfig: _config.dnsConfig
				}
				if _config.dnsPolicy != _|_ {
					dnsPolicy: _config.dnsPolicy
				}
				if _config.imagePullSecrets != _|_ {
					imagePullSecrets: _config.imagePullSecrets
				}
				securityContext: _config.podSecurityContext
				nodeSelector:    _config.nodeSelector
				if _affinity.#Enabled {
					affinity: _affinity
				}
				if _config.tolerations != _|_ {
					tolerations: _config.tolerations
				}
				if _config.topologySpreadConstraints != _|_ {
					topologySpreadConstraints: _config.topologySpreadConstraints
				}
				if _config.initContainers != _|_ {
					initContainers: _config.initContainers
				}
				containers: [
					{
						name:            "metrics-server"
						image:           _config.image.reference
						imagePullPolicy: _config.image.pullPolicy
						securityContext: _config.securityContext
						args: [
							"--secure-port=\(_config.containerPort)",
							for a in _config.defaultArgs {a},
							if _config.metrics.enabled {
								"--authorization-always-allow-paths=/metrics"
							},
							if _config.tls.type != "metrics-server" {
								"--tls-cert-file=/tmp/tls-certs/tls.crt"
							},
							if _config.tls.type != "metrics-server" {
								"--tls-private-key-file=/tmp/tls-certs/tls.key"
							},
							for a in _config.extraArgs {a},
						]
						if _config.env != _|_ {
							env: _config.env
						}
						ports: [{
							name:          "https"
							protocol:      "TCP"
							containerPort: _config.containerPort
						}]
						livenessProbe:  _config.livenessProbe
						readinessProbe: _config.readinessProbe
						// When the addon-resizer is enabled, the nanny owns the
						// container resources and patches them at runtime; rendering
						// them here would make the server-side apply fight the nanny.
						if !_config.addonResizer.enabled {
							resources: _config.resources
						}
						volumeMounts: [
							{
								name:      "tmp"
								mountPath: "/tmp"
							},
							if _config.tls.type != "metrics-server" {
								{
									name:      "certs"
									mountPath: "/tmp/tls-certs"
									readOnly:  true
								}
							},
							if _config.extraVolumeMounts != _|_ for m in _config.extraVolumeMounts {m},
						]
					},
					if _config.addonResizer.enabled {
						{
							name:            "metrics-server-nanny"
							image:           _config.addonResizer.image.reference
							imagePullPolicy: _config.addonResizer.image.pullPolicy
							securityContext: _config.addonResizer.securityContext
							env: [
								{
									name: "MY_POD_NAME"
									valueFrom: fieldRef: fieldPath: "metadata.name"
								},
								{
									name: "MY_POD_NAMESPACE"
									valueFrom: fieldRef: fieldPath: "metadata.namespace"
								},
							]
							command: [
								"/pod_nanny",
								"--config-dir=/etc/config",
								"--deployment=\(_config.metadata.name)",
								"--container=metrics-server",
								"--threshold=\(_config.addonResizer.nanny.threshold)",
								"--poll-period=\(_config.addonResizer.nanny.pollPeriod)",
								"--estimator=exponential",
								"--minClusterSize=\(_config.addonResizer.nanny.minClusterSize)",
								"--use-metrics=true",
							]
							volumeMounts: [{
								name:      "nanny-config-volume"
								mountPath: "/etc/config"
							}]
							resources: _config.addonResizer.resources
						}
					},
					if _config.extraContainers != _|_ for c in _config.extraContainers {c},
				]
				volumes: [
					{
						name: "tmp"
						_config.tmpVolume
					},
					if _config.addonResizer.enabled {
						{
							name: "nanny-config-volume"
							configMap: name: "\(_config.metadata.name)-nanny-config"
						}
					},
					if _config.tls.type != "metrics-server" {
						{
							name: "certs"
							secret: secretName: _certsSecretName
						}
					},
					if _config.extraVolumes != _|_ for v in _config.extraVolumes {v},
				]
			}
		}
	}
}
