package templates

import (
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
)

#Deployment: appsv1.#Deployment & {
	_config:    #Config
	apiVersion: "apps/v1"
	kind:       "Deployment"
	metadata:   _config.metadata
	if _config.deploymentAnnotations != _|_ {
		metadata: annotations: _config.deploymentAnnotations
	}

	// The TLS certificates secret mounted when the certificate
	// is not generated by metrics-server itself.
	_certsSecretName: [
		if _config.tls.type == "existingSecret" && _config.tls.existingSecret.name != "" {
			_config.tls.existingSecret.name
		},
		_config.metadata.name,
	][0]

	spec: appsv1.#DeploymentSpec & {
		replicas: _config.replicas
		if _config.revisionHistoryLimit != _|_ {
			revisionHistoryLimit: _config.revisionHistoryLimit
		}
		if _config.updateStrategy != _|_ {
			strategy: _config.updateStrategy
		}
		selector: matchLabels: _config.selector.labels
		template: {
			metadata: {
				labels: _config.selector.labels
				if _config.podLabels != _|_ {
					labels: _config.podLabels
				}
				if _config.podAnnotations != _|_ {
					annotations: _config.podAnnotations
				}
			}
			spec: corev1.#PodSpec & {
				serviceAccountName: _config.serviceAccount.name
				priorityClassName:  _config.priorityClassName
				if _config.hostNetwork {
					hostNetwork: true
				}
				if _config.schedulerName != _|_ {
					schedulerName: _config.schedulerName
				}
				if _config.dnsConfig != _|_ {
					dnsConfig: _config.dnsConfig
				}
				if _config.imagePullSecrets != _|_ {
					imagePullSecrets: _config.imagePullSecrets
				}
				if _config.podSecurityContext != _|_ {
					securityContext: _config.podSecurityContext
				}
				if _config.nodeSelector != _|_ {
					nodeSelector: _config.nodeSelector
				}
				affinity: _config.affinity
				if _config.tolerations != _|_ {
					tolerations: _config.tolerations
				}
				if _config.topologySpreadConstraints != _|_ {
					topologySpreadConstraints: _config.topologySpreadConstraints
				}
				containers: [
					{
						name:            "metrics-server"
						image:           _config.image.reference
						imagePullPolicy: _config.image.pullPolicy
						securityContext: _config.securityContext
						args: [
							"--secure-port=\(_config.containerPort)",
							for a in _config.defaultArgs {a},
							if _config.metrics.enabled {
								"--authorization-always-allow-paths=/metrics"
							},
							if _config.tls.type != "metrics-server" {
								"--tls-cert-file=/tmp/tls-certs/tls.crt"
							},
							if _config.tls.type != "metrics-server" {
								"--tls-private-key-file=/tmp/tls-certs/tls.key"
							},
							for a in _config.args {a},
						]
						ports: [{
							name:          "https"
							protocol:      "TCP"
							containerPort: _config.containerPort
						}]
						livenessProbe:  _config.livenessProbe
						readinessProbe: _config.readinessProbe
						resources:      _config.resources
						volumeMounts: [
							{
								name:      "tmp"
								mountPath: "/tmp"
							},
							if _config.tls.type != "metrics-server" {
								{
									name:      "certs"
									mountPath: "/tmp/tls-certs"
									readOnly:  true
								}
							},
							if _config.extraVolumeMounts != _|_ for m in _config.extraVolumeMounts {m},
						]
					},
					if _config.addonResizer.enabled {
						{
							name:            "metrics-server-nanny"
							image:           _config.addonResizer.image.reference
							imagePullPolicy: _config.addonResizer.image.pullPolicy
							securityContext: _config.addonResizer.securityContext
							env: [
								{
									name: "MY_POD_NAME"
									valueFrom: fieldRef: fieldPath: "metadata.name"
								},
								{
									name: "MY_POD_NAMESPACE"
									valueFrom: fieldRef: fieldPath: "metadata.namespace"
								},
							]
							command: [
								"/pod_nanny",
								"--config-dir=/etc/config",
								"--deployment=\(_config.metadata.name)",
								"--container=metrics-server",
								"--threshold=\(_config.addonResizer.nanny.threshold)",
								"--poll-period=\(_config.addonResizer.nanny.pollPeriod)",
								"--estimator=exponential",
								"--minClusterSize=\(_config.addonResizer.nanny.minClusterSize)",
								"--use-metrics=true",
							]
							volumeMounts: [{
								name:      "nanny-config-volume"
								mountPath: "/etc/config"
							}]
							resources: _config.addonResizer.resources
						}
					},
				]
				volumes: [
					{
						name: "tmp"
						_config.tmpVolume
					},
					if _config.addonResizer.enabled {
						{
							name: "nanny-config-volume"
							configMap: name: "\(_config.metadata.name)-nanny"
						}
					},
					if _config.tls.type != "metrics-server" {
						{
							name: "certs"
							secret: secretName: _certsSecretName
						}
					},
					if _config.extraVolumes != _|_ for v in _config.extraVolumes {v},
				]
			}
		}
	}
}
