// Code generated by upengine. DO NOT EDIT.

package templates

// The container images tracked from the upstream releases.
#defaultImages: {
	"metrics-server": {
		repository: "registry.k8s.io/metrics-server/metrics-server"
		tag:        "v0.9.0"
		digest:     ""
	}
	"addon-resizer": {
		repository: "registry.k8s.io/autoscaling/addon-resizer"
		tag:        "1.8.24"
		digest:     ""
	}
}
