// Code generated by upengine. DO NOT EDIT.

package main

// The container images tracked from the upstream releases.
values: {
	image: {
		repository: *"registry.k8s.io/metrics-server/metrics-server" | string
		tag:        *"v0.9.0" | string
		digest:     *"sha256:d9862115e7c7881280d3d75ca26bda8ffc0fc213315979575bf23ce9826205c0" | string
	}
	addonResizer: image: {
		repository: *"registry.k8s.io/autoscaling/addon-resizer" | string
		tag:        *"1.8.24" | string
		digest:     *"sha256:bcf3d19331e8cb1adf7e834aac0c7a98653bb27604d36482a2fa888dc566463a" | string
	}
}
